spring:
  datasource:
    url: jdbc:mysql:///mybatis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: \*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      aop-patterns: "xyx.mwszksnmdys.admin.*"
      filters: stat, wall


  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: jedis
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true

# 配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    myservice:
      enabled: true
  info:
    env:
      enabled: true
info:
  appName: "Boot-Admin"
  appVersion: "1.0.0"
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@