person:
  userName: 张三
  boss: true
  birth: 2019/12/9
  age: 19
  interests:
    - 篮球
    - 羽毛球
    - 乒乓球
  animal: [猫, 狗]
  score:
    english: 80
    math: 90
    chinese: 100
  salaries:
    - 999.98
    - 9999.9
  pet:
    name: 狗
    weight: 99.99
#  private Map<String, List<Pet>> allPets;
  allPets:
    rabbit:
      - {name: 小白, weight: 22}
      - name: 小绿
        weight: 33
    dog:
      - {name: 小黑, weight: 55}
      - {name: 狗, weight: 155}
    cat:
      - {name: 小花, weight: 11}
      - {name: 猫, weight: 15}
